const productRouer = require("./product.route");
const homeRouter = require("./home.route");
const search = require("./search.route");
const category = require("./category.route");
const cartRouter = require("./cart.route");
const checkOutRouter = require("./checkout.route");
const userRoure = require("./user.route");
const tableRouter = require("./table.route");
const restaurantRouter = require("./restaurant.route");
const paymentRouter = require("./payment.route");
const vendorRouter = require("./vendor.route");
const recommendationRouter = require("./recommendation.route");
const feedbackRouter = require("./feedback.route");
const foodSuggestionRouter = require("./foodsugGestion");
const searchHistoryRouter = require("./searchHistory.route");
const visitRouter = require("./visit.route");
const policyRouter = require("./policy.route");
const aiRouter = require("./ai.route");

module.exports = (app) => {
    app.use("/api", homeRouter);
    app.use("/api", productRouer);
    app.use("/api", search);
    app.use("/api", category);
    app.use("/api", cartRouter);
    app.use("/api", checkOutRouter);
    app.use("/api", userRoure);
    app.use("/api", foodSuggestionRouter);
    app.use("/api", tableRouter);
    app.use("/api", restaurantRouter);
    app.use("/api/payment", paymentRouter);
    app.use("/api/vendor", vendorRouter);
    app.use("/api/recommend", recommendationRouter);
    app.use("/api/feedback", feedbackRouter);
    app.use("/api/search-history", searchHistoryRouter);
    app.use("/api/visit", visitRouter);
    app.use("/api/policies", policyRouter);
    app.use("/api/ai", aiRouter);
};
